name: Python App Run Pytest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  testing:
    strategy:
      matrix:
        python-version:
          - "3.10"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: python3 -m pip install -r src/requirements.txt

      - name: Run pytest
        run: pytest

  release:
    needs: [ testing ]
    runs-on: ubuntu-latest
    steps:
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: test
          password: test

      - name: Pushing Docker Image
        id: docker_build
        uses: docker/build-push-action@v2