name: Python App Run Pytest
on:
  push:
    branches:
      - "*"
    branches-ignore: [ master ]
jobs:
  testing:
    strategy:
      matrix:
        python-version:
          - "3.10"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: python3 -m pip install -r src/requirements.txt

      - name: Run pytest
        run: pytest


